[package]
name = "beepbox-synthesizer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
backtrace = "0.3"
gdnative = "0.10"
once_cell = "1"
v8 = "0.43"
