[package]
name = "beepbox-synthesizer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master"}
once_cell = "1"
anyhow = "1"
v8 = "0.81"

[features]
default = ["anyhow/backtrace"]
